'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Almacen
    Public Property ID As Integer
    Public Property SucursalID As Integer
    Public Property direccion As String

    Public Overridable Property InventarioAlmacen As ICollection(Of InventarioAlmacen) = New HashSet(Of InventarioAlmacen)
    Public Overridable Property Sucursal As Sucursal

End Class
