'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Asistencia
    Public Property ID As Integer
    Public Property estatus As Boolean
    Public Property fecha_creacion As Date

    Public Overridable Property EmpleadoAsistencia As ICollection(Of EmpleadoAsistencia) = New HashSet(Of EmpleadoAsistencia)

End Class
