'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Caja
    Public Property ID As Integer
    Public Property SucursalID As Integer
    Public Property EmpleadoID As Integer

    Public Overridable Property CorteCaja As ICollection(Of CorteCaja) = New HashSet(Of CorteCaja)
    Public Overridable Property Depositos As ICollection(Of Depositos) = New HashSet(Of Depositos)
    Public Overridable Property RetirosParciales As ICollection(Of RetirosParciales) = New HashSet(Of RetirosParciales)
    Public Overridable Property Empleado As Empleado
    Public Overridable Property Sucursal As Sucursal

End Class
