'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property ID As Integer
    Public Property nombre As String
    Public Property apellidos As String
    Public Property fechaNacimiento As Date
    Public Property telefono As Integer
    Public Property direccion As String
    Public Property TipoClienteID As Integer

    Public Overridable Property Pedido As ICollection(Of Pedido) = New HashSet(Of Pedido)
    Public Overridable Property Factura As ICollection(Of Factura) = New HashSet(Of Factura)
    Public Overridable Property Reservacion As ICollection(Of Reservacion) = New HashSet(Of Reservacion)
    Public Overridable Property TarjetaCliente As ICollection(Of TarjetaCliente) = New HashSet(Of TarjetaCliente)
    Public Overridable Property Ventas_log As ICollection(Of Ventas_log) = New HashSet(Of Ventas_log)
    Public Overridable Property TipoCliente As TipoCliente

End Class
