'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property ID As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property fechaNacimiento As Date
    Public Property telefono As Integer
    Public Property direccion As String

    Public Overridable Property Caja As ICollection(Of Caja) = New HashSet(Of Caja)
    Public Overridable Property CorteCaja As ICollection(Of CorteCaja) = New HashSet(Of CorteCaja)
    Public Overridable Property Depositos As ICollection(Of Depositos) = New HashSet(Of Depositos)
    Public Overridable Property Pedido As ICollection(Of Pedido) = New HashSet(Of Pedido)
    Public Overridable Property EmpleadoAsistencia As ICollection(Of EmpleadoAsistencia) = New HashSet(Of EmpleadoAsistencia)
    Public Overridable Property Ventas_log As ICollection(Of Ventas_log) = New HashSet(Of Ventas_log)
    Public Overridable Property Factura As ICollection(Of Factura) = New HashSet(Of Factura)
    Public Overridable Property Venta As ICollection(Of Venta) = New HashSet(Of Venta)
    Public Overridable Property Repartidor As ICollection(Of Repartidor) = New HashSet(Of Repartidor)
    Public Overridable Property RetirosParciales As ICollection(Of RetirosParciales) = New HashSet(Of RetirosParciales)
    Public Overridable Property Huella_Digital As ICollection(Of Huella_Digital) = New HashSet(Of Huella_Digital)

End Class
