'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Huella_Digital
    Public Property ID As Integer
    Public Property EmpleadoID As Integer
    Public Property huella As Byte()

    Public Overridable Property Empleado As Empleado

End Class
