'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ingrediente
    Public Property ID As Integer
    Public Property nombre As String
    Public Property descripcion As String
    Public Property tamaño As String
    Public Property TipoIngredienteID As Nullable(Of Integer)
    Public Property precio As Nullable(Of Decimal)
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property InventarioIngrediente As ICollection(Of InventarioIngrediente) = New HashSet(Of InventarioIngrediente)
    Public Overridable Property TipoIngrediente As TipoIngrediente

End Class
