'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventarioIngrediente
    Public Property ID As Integer
    Public Property FechaLlegada As Date
    Public Property caducidad As Date
    Public Property InventarioID As Integer
    Public Property IngredienteID As Integer
    Public Property stock As Integer
    Public Property estado As Boolean

    Public Overridable Property Ingrediente As Ingrediente
    Public Overridable Property Inventario As Inventario

End Class
