'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InventarioAlmacen
    Public Property ID As Integer
    Public Property InventarioID As Integer
    Public Property AlmacenID As Integer

    Public Overridable Property Almacen As Almacen
    Public Overridable Property Inventario As Inventario

End Class
