'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mesa
    Public Property ID As Integer
    Public Property SucursalID As Integer
    Public Property Capacidad As Integer
    Public Property estado As Boolean

    Public Overridable Property Pedido As ICollection(Of Pedido) = New HashSet(Of Pedido)
    Public Overridable Property Propina As ICollection(Of Propina) = New HashSet(Of Propina)
    Public Overridable Property ReservaMesa As ICollection(Of ReservaMesa) = New HashSet(Of ReservaMesa)
    Public Overridable Property SucursalMesa As ICollection(Of SucursalMesa) = New HashSet(Of SucursalMesa)

End Class
