'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class RestauranteBDEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RestauranteBDEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Almacen() As DbSet(Of Almacen)
    Public Overridable Property Asistencia() As DbSet(Of Asistencia)
    Public Overridable Property Caja() As DbSet(Of Caja)
    Public Overridable Property Cancelaciones() As DbSet(Of Cancelaciones)
    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property CorteCaja() As DbSet(Of CorteCaja)
    Public Overridable Property Depositos() As DbSet(Of Depositos)
    Public Overridable Property Empleado() As DbSet(Of Empleado)
    Public Overridable Property EmpleadoAsistencia() As DbSet(Of EmpleadoAsistencia)
    Public Overridable Property EstadoPedido() As DbSet(Of EstadoPedido)
    Public Overridable Property Huella_Digital() As DbSet(Of Huella_Digital)
    Public Overridable Property Ingrediente() As DbSet(Of Ingrediente)
    Public Overridable Property Inventario() As DbSet(Of Inventario)
    Public Overridable Property InventarioAlmacen() As DbSet(Of InventarioAlmacen)
    Public Overridable Property InventarioIngrediente() As DbSet(Of InventarioIngrediente)
    Public Overridable Property Mesa() As DbSet(Of Mesa)
    Public Overridable Property Pedido() As DbSet(Of Pedido)
    Public Overridable Property PedidoProducto() As DbSet(Of PedidoProducto)
    Public Overridable Property Producto() As DbSet(Of Producto)
    Public Overridable Property Promociones() As DbSet(Of Promociones)
    Public Overridable Property PromocionProducto() As DbSet(Of PromocionProducto)
    Public Overridable Property Propina() As DbSet(Of Propina)
    Public Overridable Property Proveedores() As DbSet(Of Proveedores)
    Public Overridable Property Recetas() As DbSet(Of Recetas)
    Public Overridable Property Repartidor() As DbSet(Of Repartidor)
    Public Overridable Property Reservacion() As DbSet(Of Reservacion)
    Public Overridable Property ReservaMesa() As DbSet(Of ReservaMesa)
    Public Overridable Property RetirosParciales() As DbSet(Of RetirosParciales)
    Public Overridable Property Sucursal() As DbSet(Of Sucursal)
    Public Overridable Property SucursalMesa() As DbSet(Of SucursalMesa)
    Public Overridable Property Tarjeta() As DbSet(Of Tarjeta)
    Public Overridable Property TarjetaCliente() As DbSet(Of TarjetaCliente)
    Public Overridable Property TipoCliente() As DbSet(Of TipoCliente)
    Public Overridable Property TipoIngrediente() As DbSet(Of TipoIngrediente)
    Public Overridable Property TipoPago() As DbSet(Of TipoPago)
    Public Overridable Property TipoPrioridad() As DbSet(Of TipoPrioridad)
    Public Overridable Property TipoProducto() As DbSet(Of TipoProducto)
    Public Overridable Property TipoSucursal() As DbSet(Of TipoSucursal)
    Public Overridable Property TipoVehiculo() As DbSet(Of TipoVehiculo)
    Public Overridable Property Vehiculo() As DbSet(Of Vehiculo)
    Public Overridable Property Factura() As DbSet(Of Factura)
    Public Overridable Property Venta() As DbSet(Of Venta)
    Public Overridable Property Ventas_log() As DbSet(Of Ventas_log)
    Public Overridable Property Productodos() As DbSet(Of Productodos)

    Public Overridable Function sp_Cancelar_Pedido(idPedido As Nullable(Of Integer)) As Integer
        Dim idPedidoParameter As ObjectParameter = If(idPedido.HasValue, New ObjectParameter("idPedido", idPedido), New ObjectParameter("idPedido", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Cancelar_Pedido", idPedidoParameter)
    End Function

    Public Overridable Function sp_Inserta_Producto(nombre As String, descripcion As String, tipoProductoID As Nullable(Of Integer), precio As Nullable(Of Decimal), estado As Nullable(Of Boolean)) As Integer
        Dim nombreParameter As ObjectParameter = If(nombre IsNot Nothing, New ObjectParameter("nombre", nombre), New ObjectParameter("nombre", GetType(String)))

        Dim descripcionParameter As ObjectParameter = If(descripcion IsNot Nothing, New ObjectParameter("descripcion", descripcion), New ObjectParameter("descripcion", GetType(String)))

        Dim tipoProductoIDParameter As ObjectParameter = If(tipoProductoID.HasValue, New ObjectParameter("TipoProductoID", tipoProductoID), New ObjectParameter("TipoProductoID", GetType(Integer)))

        Dim precioParameter As ObjectParameter = If(precio.HasValue, New ObjectParameter("precio", precio), New ObjectParameter("precio", GetType(Decimal)))

        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("estado", estado), New ObjectParameter("estado", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Inserta_Producto", nombreParameter, descripcionParameter, tipoProductoIDParameter, precioParameter, estadoParameter)
    End Function

    Public Overridable Function sp_Modifica_Ingrediente(iD As Nullable(Of Integer), precio As Nullable(Of Decimal)) As Integer
        Dim iDParameter As ObjectParameter = If(iD.HasValue, New ObjectParameter("ID", iD), New ObjectParameter("ID", GetType(Integer)))

        Dim precioParameter As ObjectParameter = If(precio.HasValue, New ObjectParameter("precio", precio), New ObjectParameter("precio", GetType(Decimal)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Modifica_Ingrediente", iDParameter, precioParameter)
    End Function

    Public Overridable Function sp_New_Pedido(idPedido As Nullable(Of Integer), idMesa As Nullable(Of Integer), idcliente As Nullable(Of Integer), idEmpleado As Nullable(Of Integer), estado As Nullable(Of Integer), fecha As Nullable(Of Date)) As Integer
        Dim idPedidoParameter As ObjectParameter = If(idPedido.HasValue, New ObjectParameter("idPedido", idPedido), New ObjectParameter("idPedido", GetType(Integer)))

        Dim idMesaParameter As ObjectParameter = If(idMesa.HasValue, New ObjectParameter("idMesa", idMesa), New ObjectParameter("idMesa", GetType(Integer)))

        Dim idclienteParameter As ObjectParameter = If(idcliente.HasValue, New ObjectParameter("idcliente", idcliente), New ObjectParameter("idcliente", GetType(Integer)))

        Dim idEmpleadoParameter As ObjectParameter = If(idEmpleado.HasValue, New ObjectParameter("idEmpleado", idEmpleado), New ObjectParameter("idEmpleado", GetType(Integer)))

        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("estado", estado), New ObjectParameter("estado", GetType(Integer)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_New_Pedido", idPedidoParameter, idMesaParameter, idclienteParameter, idEmpleadoParameter, estadoParameter, fechaParameter)
    End Function

    Public Overridable Function sp_Pedido_Por_Estado(pedidoEstado As Nullable(Of Integer)) As ObjectResult(Of sp_Pedido_Por_Estado_Result)
        Dim pedidoEstadoParameter As ObjectParameter = If(pedidoEstado.HasValue, New ObjectParameter("PedidoEstado", pedidoEstado), New ObjectParameter("PedidoEstado", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_Pedido_Por_Estado_Result)("sp_Pedido_Por_Estado", pedidoEstadoParameter)
    End Function

    Public Overridable Function sp_Ventas_Por_Rango_Fecha(fechaInicial As Nullable(Of Date), fechaFinal As Nullable(Of Date)) As Integer
        Dim fechaInicialParameter As ObjectParameter = If(fechaInicial.HasValue, New ObjectParameter("fechaInicial", fechaInicial), New ObjectParameter("fechaInicial", GetType(Date)))

        Dim fechaFinalParameter As ObjectParameter = If(fechaFinal.HasValue, New ObjectParameter("fechaFinal", fechaFinal), New ObjectParameter("fechaFinal", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_Ventas_Por_Rango_Fecha", fechaInicialParameter, fechaFinalParameter)
    End Function

End Class
