'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PedidoProducto
    Public Property ID As Integer
    Public Property PedidoID As Integer
    Public Property ProductID As Integer

    Public Overridable Property Pedido As Pedido
    Public Overridable Property Producto As Producto

End Class
