'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pedido
    Public Property ID As Integer
    Public Property MesaID As Integer
    Public Property ClienteID As Integer
    Public Property EmpleadoID As Integer
    Public Property EstadoPedidoID As Integer
    Public Property Fecha As Date

    Public Overridable Property Cancelaciones As ICollection(Of Cancelaciones) = New HashSet(Of Cancelaciones)
    Public Overridable Property Cliente As Cliente
    Public Overridable Property Empleado As Empleado
    Public Overridable Property EstadoPedido As EstadoPedido
    Public Overridable Property Mesa As Mesa
    Public Overridable Property PedidoProducto As ICollection(Of PedidoProducto) = New HashSet(Of PedidoProducto)
    Public Overridable Property Venta As ICollection(Of Venta) = New HashSet(Of Venta)

End Class
