'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Productodos
    Public Property ID As Integer
    Public Property nombre As String
    Public Property descripcion As String
    Public Property TipoProductoID As Nullable(Of Integer)
    Public Property precio As Nullable(Of Decimal)
    Public Property estado As Nullable(Of Boolean)

End Class
