'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto
    Public Property ID As Integer
    Public Property nombre As String
    Public Property descripcion As String
    Public Property TipoProductoID As Nullable(Of Integer)
    Public Property precio As Nullable(Of Decimal)
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property PedidoProducto As ICollection(Of PedidoProducto) = New HashSet(Of PedidoProducto)
    Public Overridable Property PromocionProducto As ICollection(Of PromocionProducto) = New HashSet(Of PromocionProducto)
    Public Overridable Property Recetas As ICollection(Of Recetas) = New HashSet(Of Recetas)
    Public Overridable Property TipoProducto As TipoProducto

End Class
