'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PromocionProducto
    Public Property ID As Integer
    Public Property ProductoID As Integer
    Public Property PromocionID As Integer
    Public Property estado As Boolean

    Public Overridable Property Producto As Producto
    Public Overridable Property Promociones As Promociones

End Class
