'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Propina
    Public Property ID As Integer
    Public Property MesaID As Integer
    Public Property Fecha As Date
    Public Property Cantidad As Decimal

    Public Overridable Property Mesa As Mesa

End Class
