'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Reservacion
    Public Property ID As Integer
    Public Property SucursalID As Integer
    Public Property ClienteID As Integer
    Public Property FechaDeSolicitud As Date
    Public Property FechaDeReservacion As Date

    Public Overridable Property Cliente As Cliente
    Public Overridable Property ReservaMesa As ICollection(Of ReservaMesa) = New HashSet(Of ReservaMesa)
    Public Overridable Property Sucursal As Sucursal

End Class
