'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RetirosParciales
    Public Property ID As Integer
    Public Property CajaID As Integer
    Public Property EmpleadoID As Integer
    Public Property HoraFecha As Date
    Public Property DineroRetirado As Integer

    Public Overridable Property Caja As Caja
    Public Overridable Property Empleado As Empleado

End Class
