'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sucursal
    Public Property ID As Integer
    Public Property direccion As String
    Public Property telefono As Integer
    Public Property TipoSucursalID As Integer

    Public Overridable Property Almacen As ICollection(Of Almacen) = New HashSet(Of Almacen)
    Public Overridable Property Caja As ICollection(Of Caja) = New HashSet(Of Caja)
    Public Overridable Property Reservacion As ICollection(Of Reservacion) = New HashSet(Of Reservacion)
    Public Overridable Property SucursalMesa As ICollection(Of SucursalMesa) = New HashSet(Of SucursalMesa)
    Public Overridable Property TipoSucursal As TipoSucursal

End Class
