'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TarjetaCliente
    Public Property ID As Integer
    Public Property ClienteID As Integer
    Public Property TarjetaID As Integer

    Public Overridable Property Cliente As Cliente
    Public Overridable Property Tarjeta As Tarjeta

End Class
