'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tarjeta
    Public Property ID As Integer
    Public Property numerodeTarjeta As Integer
    Public Property CompañiadeTarjeta As String

    Public Overridable Property TarjetaCliente As ICollection(Of TarjetaCliente) = New HashSet(Of TarjetaCliente)

End Class
