'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoVehiculo
    Public Property ID As Integer
    Public Property tamaño As String
    Public Property marca As String
    Public Property descripcion As String

    Public Overridable Property Vehiculo As ICollection(Of Vehiculo) = New HashSet(Of Vehiculo)

End Class
