'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vehiculo
    Public Property ID As Integer
    Public Property TipoVehiculoID As Integer
    Public Property color As String
    Public Property Fecha_compra As Date

    Public Overridable Property Repartidor As ICollection(Of Repartidor) = New HashSet(Of Repartidor)
    Public Overridable Property TipoVehiculo As TipoVehiculo

End Class
